version: '3.8'
services:
  service-main:
    container_name: service-main
    image: service-main/version:1.0
    ports:
      - "8080:8080"
    environment:
      MP_JWT_VERIFY_PUBLICKEY_LOCATION: /jwt/publicKey.pem
      SMALLRYE_JWT_SIGN_KEY_LOCATION: /jwt/privateKey.pem
    volumes:
      - type: bind
        source: ./jwt
        target: /jwt
  service-gateway:
    container_name: service-gateway
    image: service-gateway/version:1.0
    ports:
      - "8082:8082"
    environment:
      MP_JWT_VERIFY_PUBLICKEY_LOCATION: /jwt/publicKey.pem
      SMALLRYE_JWT_SIGN_KEY_LOCATION: /jwt/privateKey.pem
    volumes:
      - type: bind
        source: ./jwt
        target: /jwt
